### PR TITLE
Fix navbar-bootstrap grid into layout.erb

### PR DESCRIPTION
**Pull request by sandiiarov**
Refactoring and fix bootstrap grid

### CODE REVIEW

**Comment by ro31337** [comment]
Спасибо за pull request. Можешь объяснить изменения?

**Comment by sandiiarov** [comment]
1) Первым должен идти тег nav, а потом уже тег div с классом container

Вот так:

<nav class="navbar navbar-default">
  <div class="container">
  </div>
</nav>

2) error и yield разнес по row

3) Просто отрефакторил код и стало более красиво и понятнее

**Comment by Alex4S** [comment]
Hi rubyschool-us/sinatr,

I'd like to add you to my professional network on LinkedIn.

- Alex

Confirm that you know Alex: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=q6N71FF4&invitationId=6196265694506598400&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eiunx7yqu%7Eqr








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iunx7yqu-qr&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEeb2t-iGZtjwAAAVf2PI-FlUUjbZWXZCKz73cKgK2jq3wn0yCw4HpV0blF0O44K9rxzCOLq04qzJBtu6RGlYxWKRZqGnOAzw1fFkqCQDtHRQWuaxh7QwpZqVpaSePQkrKpr8Ts9CC3-tf4vkTuW19O9PqPwZ2IEFyAoe2jEY1hqHDty_kjFn-TVSkbLHaxQeU-&eid=0-iunx7yqu-qr


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iunx7yqu-qr&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Alex4S** [comment]
Alex Sandiiarov would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=q6N71FF4&invitationId=6196265694506598400&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-me7dil%7Eiuxsxod5%7E8c

View Alex Sandiiarov&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=q6N71FF4&invitationId=6196265694506598400&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-me7dil%7Eiuxsxod5%7E8c





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=me7dil-iuxsxod5-8c&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=me7dil-iuxsxod5-8c&loid=AQHt7BgXd6dvVAAAAVga8EFyc7vekQrb-NudhTvVk8zf0iYw4CTUNLgFjV1-K_GHYPQwed3vxU84O_SwGOr6Pm_xQ0itUYF2kUuGmBUyOAwB95Lrz_W3xn9gtX-aHA0Y-8Wymdi20EfZLuE5TtjrtK78DcUTFbudW3HJ87809sTRUzqaItZcgRe-ANDR7cTAhr1x

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=me7dil-iuxsxod5-8c&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Alex4S** [comment]
Hi ,

Alex Sandiiarov would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=q6N71FF4&invitationId=6196265694506598400&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-me7dil%7Eiv8cma5a%7E2w

View Alex Sandiiarov&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=q6N71FF4&invitationId=6196265694506598400&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-me7dil%7Eiv8cma5a%7E2w





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=me7dil-iv8cma5a-2w&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=me7dil-iv8cma5a-2w&loid=AQER_3kQbod0WAAAAVhBCpJ5w8CX_FXZOo79cABVrFW7HAlKRo0b-1AUPc_p9OtSEfrYPcIT89Rq7VG5sZveJW8nsjIChH62B9iZvXNUyBR0XYtsvR3jm5e8Zd-ZXTySqHryMol677l6iZ5vV5Hp_yAtFj4ZS1G-UmNTq3i4XfuXtRk88okHq3n9SGnVgrKvKh4j

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=me7dil-iv8cma5a-2w&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
